/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is generated by scripts/generate-route-tree.mjs.
// Do not edit it manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountExportRouteImport } from './routes/api/account/export'
import { Route as ApiCronEmbrapaRouteImport } from './routes/api/cron/embrapa'
import { Route as ApiCronForecastAccuracyRouteImport } from './routes/api/cron/forecast-accuracy'
import { Route as ApiCronPushDailyRouteImport } from './routes/api/cron/push-daily'
import { Route as ApiCronWeatherSnapshotRouteImport } from './routes/api/cron/weather-snapshot'
import { Route as ApiInmetGeadasRouteImport } from './routes/api/inmet/geadas'
import { Route as ApiPushBroadcastRouteImport } from './routes/api/push/broadcast'
import { Route as ApiPushConfigRouteImport } from './routes/api/push/config'
import { Route as ApiPushSubscriptionRouteImport } from './routes/api/push/subscription'
import { Route as ApiRedemetImageRouteImport } from './routes/api/redemet/image'
import { Route as ApiRedemetRadarRouteImport } from './routes/api/redemet/radar'
import { Route as ApiRedemetSatelliteRouteImport } from './routes/api/redemet/satellite'
import { Route as ApiRedemetStormsRouteImport } from './routes/api/redemet/storms'
import { Route as ApiWeatherEmbrapaRouteImport } from './routes/api/weather/embrapa'
import { Route as ApiWeatherHourlyPrecipitationRouteImport } from './routes/api/weather/hourly-precipitation'
import { Route as ApiWidgetsNivelLaranjalRouteImport } from './routes/api/widgets/nivel-laranjal'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthSignoutRouteImport } from './routes/auth/signout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BrandTempoPelotasHeaderRouteImport } from './routes/brand/tempo-pelotas-header'
import { Route as BrandTempoPelotasIconDotPngRouteImport } from './routes/brand/tempo-pelotas-icon[.]png'
import { Route as BrandTempoPelotasMaskableDotPngRouteImport } from './routes/brand/tempo-pelotas-maskable[.]png'
import { Route as CamerasAoVivoPelotasRouteImport } from './routes/cameras-ao-vivo-pelotas'
import { Route as ChuvaEmPelotasRouteImport } from './routes/chuva-em-pelotas'
import { Route as ClimaEmPelotasRouteImport } from './routes/clima-em-pelotas'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EmbedNivelLaranjalRouteImport } from './routes/embed/nivel-laranjal'
import { Route as EmbedStatusTempoAgoraRouteImport } from './routes/embed/status-tempo-agora'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstacaoEmbrapaPelotasRouteImport } from './routes/estacao-embrapa-pelotas'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as HistoricoClimaticoPelotasRouteImport } from './routes/historico-climatico-pelotas'
import { Route as MapaDeGeadasRioGrandeDoSulRouteImport } from './routes/mapa-de-geadas-rio-grande-do-sul'
import { Route as MeteogramaPelotasRouteImport } from './routes/meteograma-pelotas'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as NivelDaLagoaDosPatosLaranjalRouteImport } from './routes/nivel-da-lagoa-dos-patos-laranjal'
import { Route as PelotasDotJsonRouteImport } from './routes/pelotas[.]json'
import { Route as Previsao7DiasPelotasRouteImport } from './routes/previsao-7-dias-pelotas'
import { Route as PrivacidadeEDadosRouteImport } from './routes/privacidade-e-dados'
import { Route as RadarESatelitePelotasRouteImport } from './routes/radar-e-satelite-pelotas'
import { Route as RobotsDotTxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotXmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SituacaoHidrologicaPelotasRouteImport } from './routes/situacao-hidrologica-pelotas'
import { Route as TempoAmanhaPelotasRouteImport } from './routes/tempo-amanha-pelotas'
import { Route as TempoEmCitySlugRouteImport } from './routes/tempo-em/$citySlug'
import { Route as TempoHojePelotasRouteImport } from './routes/tempo-hoje-pelotas'
import { Route as TempoNaRegiaoSulRsRouteImport } from './routes/tempo-na-regiao-sul-rs'
import { Route as VentoEmPelotasRouteImport } from './routes/vento-em-pelotas'
import { Route as WidgetsNivelLaranjalDotJsRouteImport } from './routes/widgets/nivel-laranjal[.]js'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiCronEmbrapaRoute = ApiCronEmbrapaRouteImport.update({
  id: '/api/cron/embrapa',
  path: '/api/cron/embrapa',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiCronForecastAccuracyRoute = ApiCronForecastAccuracyRouteImport.update({
  id: '/api/cron/forecast-accuracy',
  path: '/api/cron/forecast-accuracy',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiCronPushDailyRoute = ApiCronPushDailyRouteImport.update({
  id: '/api/cron/push-daily',
  path: '/api/cron/push-daily',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiCronWeatherSnapshotRoute = ApiCronWeatherSnapshotRouteImport.update({
  id: '/api/cron/weather-snapshot',
  path: '/api/cron/weather-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiInmetGeadasRoute = ApiInmetGeadasRouteImport.update({
  id: '/api/inmet/geadas',
  path: '/api/inmet/geadas',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiPushBroadcastRoute = ApiPushBroadcastRouteImport.update({
  id: '/api/push/broadcast',
  path: '/api/push/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiPushConfigRoute = ApiPushConfigRouteImport.update({
  id: '/api/push/config',
  path: '/api/push/config',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiPushSubscriptionRoute = ApiPushSubscriptionRouteImport.update({
  id: '/api/push/subscription',
  path: '/api/push/subscription',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiRedemetImageRoute = ApiRedemetImageRouteImport.update({
  id: '/api/redemet/image',
  path: '/api/redemet/image',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiRedemetRadarRoute = ApiRedemetRadarRouteImport.update({
  id: '/api/redemet/radar',
  path: '/api/redemet/radar',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiRedemetSatelliteRoute = ApiRedemetSatelliteRouteImport.update({
  id: '/api/redemet/satellite',
  path: '/api/redemet/satellite',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiRedemetStormsRoute = ApiRedemetStormsRouteImport.update({
  id: '/api/redemet/storms',
  path: '/api/redemet/storms',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiWeatherEmbrapaRoute = ApiWeatherEmbrapaRouteImport.update({
  id: '/api/weather/embrapa',
  path: '/api/weather/embrapa',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiWeatherHourlyPrecipitationRoute = ApiWeatherHourlyPrecipitationRouteImport.update({
  id: '/api/weather/hourly-precipitation',
  path: '/api/weather/hourly-precipitation',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiWidgetsNivelLaranjalRoute = ApiWidgetsNivelLaranjalRouteImport.update({
  id: '/api/widgets/nivel-laranjal',
  path: '/api/widgets/nivel-laranjal',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/auth/signout',
  path: '/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)

const BrandTempoPelotasHeaderRoute = BrandTempoPelotasHeaderRouteImport.update({
  id: '/brand/tempo-pelotas-header',
  path: '/brand/tempo-pelotas-header',
  getParentRoute: () => rootRouteImport,
} as any)

const BrandTempoPelotasIconDotPngRoute = BrandTempoPelotasIconDotPngRouteImport.update({
  id: '/brand/tempo-pelotas-icon.png',
  path: '/brand/tempo-pelotas-icon.png',
  getParentRoute: () => rootRouteImport,
} as any)

const BrandTempoPelotasMaskableDotPngRoute = BrandTempoPelotasMaskableDotPngRouteImport.update({
  id: '/brand/tempo-pelotas-maskable.png',
  path: '/brand/tempo-pelotas-maskable.png',
  getParentRoute: () => rootRouteImport,
} as any)

const CamerasAoVivoPelotasRoute = CamerasAoVivoPelotasRouteImport.update({
  id: '/cameras-ao-vivo-pelotas',
  path: '/cameras-ao-vivo-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const ChuvaEmPelotasRoute = ChuvaEmPelotasRouteImport.update({
  id: '/chuva-em-pelotas',
  path: '/chuva-em-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const ClimaEmPelotasRoute = ClimaEmPelotasRouteImport.update({
  id: '/clima-em-pelotas',
  path: '/clima-em-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)

const EmbedNivelLaranjalRoute = EmbedNivelLaranjalRouteImport.update({
  id: '/embed/nivel-laranjal',
  path: '/embed/nivel-laranjal',
  getParentRoute: () => rootRouteImport,
} as any)

const EmbedStatusTempoAgoraRoute = EmbedStatusTempoAgoraRouteImport.update({
  id: '/embed/status-tempo-agora',
  path: '/embed/status-tempo-agora',
  getParentRoute: () => rootRouteImport,
} as any)

const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)

const EstacaoEmbrapaPelotasRoute = EstacaoEmbrapaPelotasRouteImport.update({
  id: '/estacao-embrapa-pelotas',
  path: '/estacao-embrapa-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)

const HistoricoClimaticoPelotasRoute = HistoricoClimaticoPelotasRouteImport.update({
  id: '/historico-climatico-pelotas',
  path: '/historico-climatico-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const MapaDeGeadasRioGrandeDoSulRoute = MapaDeGeadasRioGrandeDoSulRouteImport.update({
  id: '/mapa-de-geadas-rio-grande-do-sul',
  path: '/mapa-de-geadas-rio-grande-do-sul',
  getParentRoute: () => rootRouteImport,
} as any)

const MeteogramaPelotasRoute = MeteogramaPelotasRouteImport.update({
  id: '/meteograma-pelotas',
  path: '/meteograma-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)

const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)

const NivelDaLagoaDosPatosLaranjalRoute = NivelDaLagoaDosPatosLaranjalRouteImport.update({
  id: '/nivel-da-lagoa-dos-patos-laranjal',
  path: '/nivel-da-lagoa-dos-patos-laranjal',
  getParentRoute: () => rootRouteImport,
} as any)

const PelotasDotJsonRoute = PelotasDotJsonRouteImport.update({
  id: '/pelotas.json',
  path: '/pelotas.json',
  getParentRoute: () => rootRouteImport,
} as any)

const Previsao7DiasPelotasRoute = Previsao7DiasPelotasRouteImport.update({
  id: '/previsao-7-dias-pelotas',
  path: '/previsao-7-dias-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const PrivacidadeEDadosRoute = PrivacidadeEDadosRouteImport.update({
  id: '/privacidade-e-dados',
  path: '/privacidade-e-dados',
  getParentRoute: () => rootRouteImport,
} as any)

const RadarESatelitePelotasRoute = RadarESatelitePelotasRouteImport.update({
  id: '/radar-e-satelite-pelotas',
  path: '/radar-e-satelite-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const RobotsDotTxtRoute = RobotsDotTxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)

const SitemapDotXmlRoute = SitemapDotXmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

const SituacaoHidrologicaPelotasRoute = SituacaoHidrologicaPelotasRouteImport.update({
  id: '/situacao-hidrologica-pelotas',
  path: '/situacao-hidrologica-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const TempoAmanhaPelotasRoute = TempoAmanhaPelotasRouteImport.update({
  id: '/tempo-amanha-pelotas',
  path: '/tempo-amanha-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const TempoEmCitySlugRoute = TempoEmCitySlugRouteImport.update({
  id: '/tempo-em/$citySlug',
  path: '/tempo-em/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)

const TempoHojePelotasRoute = TempoHojePelotasRouteImport.update({
  id: '/tempo-hoje-pelotas',
  path: '/tempo-hoje-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const TempoNaRegiaoSulRsRoute = TempoNaRegiaoSulRsRouteImport.update({
  id: '/tempo-na-regiao-sul-rs',
  path: '/tempo-na-regiao-sul-rs',
  getParentRoute: () => rootRouteImport,
} as any)

const VentoEmPelotasRoute = VentoEmPelotasRouteImport.update({
  id: '/vento-em-pelotas',
  path: '/vento-em-pelotas',
  getParentRoute: () => rootRouteImport,
} as any)

const WidgetsNivelLaranjalDotJsRoute = WidgetsNivelLaranjalDotJsRouteImport.update({
  id: '/widgets/nivel-laranjal.js',
  path: '/widgets/nivel-laranjal.js',
  getParentRoute: () => rootRouteImport,
} as any)

type RouteMap = {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/cron/embrapa': typeof ApiCronEmbrapaRoute
  '/api/cron/forecast-accuracy': typeof ApiCronForecastAccuracyRoute
  '/api/cron/push-daily': typeof ApiCronPushDailyRoute
  '/api/cron/weather-snapshot': typeof ApiCronWeatherSnapshotRoute
  '/api/inmet/geadas': typeof ApiInmetGeadasRoute
  '/api/push/broadcast': typeof ApiPushBroadcastRoute
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/redemet/image': typeof ApiRedemetImageRoute
  '/api/redemet/radar': typeof ApiRedemetRadarRoute
  '/api/redemet/satellite': typeof ApiRedemetSatelliteRoute
  '/api/redemet/storms': typeof ApiRedemetStormsRoute
  '/api/weather/embrapa': typeof ApiWeatherEmbrapaRoute
  '/api/weather/hourly-precipitation': typeof ApiWeatherHourlyPrecipitationRoute
  '/api/widgets/nivel-laranjal': typeof ApiWidgetsNivelLaranjalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/blog': typeof BlogRoute
  '/brand/tempo-pelotas-header': typeof BrandTempoPelotasHeaderRoute
  '/brand/tempo-pelotas-icon.png': typeof BrandTempoPelotasIconDotPngRoute
  '/brand/tempo-pelotas-maskable.png': typeof BrandTempoPelotasMaskableDotPngRoute
  '/cameras-ao-vivo-pelotas': typeof CamerasAoVivoPelotasRoute
  '/chuva-em-pelotas': typeof ChuvaEmPelotasRoute
  '/clima-em-pelotas': typeof ClimaEmPelotasRoute
  '/conta': typeof ContaRoute
  '/embed/nivel-laranjal': typeof EmbedNivelLaranjalRoute
  '/embed/status-tempo-agora': typeof EmbedStatusTempoAgoraRoute
  '/entrar': typeof EntrarRoute
  '/estacao-embrapa-pelotas': typeof EstacaoEmbrapaPelotasRoute
  '/feed': typeof FeedRoute
  '/historico-climatico-pelotas': typeof HistoricoClimaticoPelotasRoute
  '/mapa-de-geadas-rio-grande-do-sul': typeof MapaDeGeadasRioGrandeDoSulRoute
  '/meteograma-pelotas': typeof MeteogramaPelotasRoute
  '/metodologia': typeof MetodologiaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/nivel-da-lagoa-dos-patos-laranjal': typeof NivelDaLagoaDosPatosLaranjalRoute
  '/pelotas.json': typeof PelotasDotJsonRoute
  '/previsao-7-dias-pelotas': typeof Previsao7DiasPelotasRoute
  '/privacidade-e-dados': typeof PrivacidadeEDadosRoute
  '/radar-e-satelite-pelotas': typeof RadarESatelitePelotasRoute
  '/robots.txt': typeof RobotsDotTxtRoute
  '/sitemap.xml': typeof SitemapDotXmlRoute
  '/situacao-hidrologica-pelotas': typeof SituacaoHidrologicaPelotasRoute
  '/tempo-amanha-pelotas': typeof TempoAmanhaPelotasRoute
  '/tempo-em/$citySlug': typeof TempoEmCitySlugRoute
  '/tempo-hoje-pelotas': typeof TempoHojePelotasRoute
  '/tempo-na-regiao-sul-rs': typeof TempoNaRegiaoSulRsRoute
  '/vento-em-pelotas': typeof VentoEmPelotasRoute
  '/widgets/nivel-laranjal.js': typeof WidgetsNivelLaranjalDotJsRoute
}

type RoutePath = keyof RouteMap
type FileRoutesByFullPath = RouteMap
type FileRoutesByTo = RouteMap
type FileRoutesById = { __root__: typeof rootRouteImport } & RouteMap

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: RoutePath
  fileRoutesByTo: FileRoutesByTo
  to: RoutePath
  id: '__root__' | RoutePath
  fileRoutesById: FileRoutesById
}

type GeneratedFileRoute<Path extends string, RouteImport> = {
  id: Path
  path: Path
  fullPath: Path
  preLoaderRoute: RouteImport
  parentRoute: typeof rootRouteImport
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': GeneratedFileRoute<'/', typeof IndexRouteImport>
    '/alertas': GeneratedFileRoute<'/alertas', typeof AlertasRouteImport>
    '/api/account/delete': GeneratedFileRoute<'/api/account/delete', typeof ApiAccountDeleteRouteImport>
    '/api/account/export': GeneratedFileRoute<'/api/account/export', typeof ApiAccountExportRouteImport>
    '/api/cron/embrapa': GeneratedFileRoute<'/api/cron/embrapa', typeof ApiCronEmbrapaRouteImport>
    '/api/cron/forecast-accuracy': GeneratedFileRoute<'/api/cron/forecast-accuracy', typeof ApiCronForecastAccuracyRouteImport>
    '/api/cron/push-daily': GeneratedFileRoute<'/api/cron/push-daily', typeof ApiCronPushDailyRouteImport>
    '/api/cron/weather-snapshot': GeneratedFileRoute<'/api/cron/weather-snapshot', typeof ApiCronWeatherSnapshotRouteImport>
    '/api/inmet/geadas': GeneratedFileRoute<'/api/inmet/geadas', typeof ApiInmetGeadasRouteImport>
    '/api/push/broadcast': GeneratedFileRoute<'/api/push/broadcast', typeof ApiPushBroadcastRouteImport>
    '/api/push/config': GeneratedFileRoute<'/api/push/config', typeof ApiPushConfigRouteImport>
    '/api/push/subscription': GeneratedFileRoute<'/api/push/subscription', typeof ApiPushSubscriptionRouteImport>
    '/api/redemet/image': GeneratedFileRoute<'/api/redemet/image', typeof ApiRedemetImageRouteImport>
    '/api/redemet/radar': GeneratedFileRoute<'/api/redemet/radar', typeof ApiRedemetRadarRouteImport>
    '/api/redemet/satellite': GeneratedFileRoute<'/api/redemet/satellite', typeof ApiRedemetSatelliteRouteImport>
    '/api/redemet/storms': GeneratedFileRoute<'/api/redemet/storms', typeof ApiRedemetStormsRouteImport>
    '/api/weather/embrapa': GeneratedFileRoute<'/api/weather/embrapa', typeof ApiWeatherEmbrapaRouteImport>
    '/api/weather/hourly-precipitation': GeneratedFileRoute<'/api/weather/hourly-precipitation', typeof ApiWeatherHourlyPrecipitationRouteImport>
    '/api/widgets/nivel-laranjal': GeneratedFileRoute<'/api/widgets/nivel-laranjal', typeof ApiWidgetsNivelLaranjalRouteImport>
    '/auth/callback': GeneratedFileRoute<'/auth/callback', typeof AuthCallbackRouteImport>
    '/auth/signout': GeneratedFileRoute<'/auth/signout', typeof AuthSignoutRouteImport>
    '/blog': GeneratedFileRoute<'/blog', typeof BlogRouteImport>
    '/brand/tempo-pelotas-header': GeneratedFileRoute<'/brand/tempo-pelotas-header', typeof BrandTempoPelotasHeaderRouteImport>
    '/brand/tempo-pelotas-icon.png': GeneratedFileRoute<'/brand/tempo-pelotas-icon.png', typeof BrandTempoPelotasIconDotPngRouteImport>
    '/brand/tempo-pelotas-maskable.png': GeneratedFileRoute<'/brand/tempo-pelotas-maskable.png', typeof BrandTempoPelotasMaskableDotPngRouteImport>
    '/cameras-ao-vivo-pelotas': GeneratedFileRoute<'/cameras-ao-vivo-pelotas', typeof CamerasAoVivoPelotasRouteImport>
    '/chuva-em-pelotas': GeneratedFileRoute<'/chuva-em-pelotas', typeof ChuvaEmPelotasRouteImport>
    '/clima-em-pelotas': GeneratedFileRoute<'/clima-em-pelotas', typeof ClimaEmPelotasRouteImport>
    '/conta': GeneratedFileRoute<'/conta', typeof ContaRouteImport>
    '/embed/nivel-laranjal': GeneratedFileRoute<'/embed/nivel-laranjal', typeof EmbedNivelLaranjalRouteImport>
    '/embed/status-tempo-agora': GeneratedFileRoute<'/embed/status-tempo-agora', typeof EmbedStatusTempoAgoraRouteImport>
    '/entrar': GeneratedFileRoute<'/entrar', typeof EntrarRouteImport>
    '/estacao-embrapa-pelotas': GeneratedFileRoute<'/estacao-embrapa-pelotas', typeof EstacaoEmbrapaPelotasRouteImport>
    '/feed': GeneratedFileRoute<'/feed', typeof FeedRouteImport>
    '/historico-climatico-pelotas': GeneratedFileRoute<'/historico-climatico-pelotas', typeof HistoricoClimaticoPelotasRouteImport>
    '/mapa-de-geadas-rio-grande-do-sul': GeneratedFileRoute<'/mapa-de-geadas-rio-grande-do-sul', typeof MapaDeGeadasRioGrandeDoSulRouteImport>
    '/meteograma-pelotas': GeneratedFileRoute<'/meteograma-pelotas', typeof MeteogramaPelotasRouteImport>
    '/metodologia': GeneratedFileRoute<'/metodologia', typeof MetodologiaRouteImport>
    '/minha-conta': GeneratedFileRoute<'/minha-conta', typeof MinhaContaRouteImport>
    '/nivel-da-lagoa-dos-patos-laranjal': GeneratedFileRoute<'/nivel-da-lagoa-dos-patos-laranjal', typeof NivelDaLagoaDosPatosLaranjalRouteImport>
    '/pelotas.json': GeneratedFileRoute<'/pelotas.json', typeof PelotasDotJsonRouteImport>
    '/previsao-7-dias-pelotas': GeneratedFileRoute<'/previsao-7-dias-pelotas', typeof Previsao7DiasPelotasRouteImport>
    '/privacidade-e-dados': GeneratedFileRoute<'/privacidade-e-dados', typeof PrivacidadeEDadosRouteImport>
    '/radar-e-satelite-pelotas': GeneratedFileRoute<'/radar-e-satelite-pelotas', typeof RadarESatelitePelotasRouteImport>
    '/robots.txt': GeneratedFileRoute<'/robots.txt', typeof RobotsDotTxtRouteImport>
    '/sitemap.xml': GeneratedFileRoute<'/sitemap.xml', typeof SitemapDotXmlRouteImport>
    '/situacao-hidrologica-pelotas': GeneratedFileRoute<'/situacao-hidrologica-pelotas', typeof SituacaoHidrologicaPelotasRouteImport>
    '/tempo-amanha-pelotas': GeneratedFileRoute<'/tempo-amanha-pelotas', typeof TempoAmanhaPelotasRouteImport>
    '/tempo-em/$citySlug': GeneratedFileRoute<'/tempo-em/$citySlug', typeof TempoEmCitySlugRouteImport>
    '/tempo-hoje-pelotas': GeneratedFileRoute<'/tempo-hoje-pelotas', typeof TempoHojePelotasRouteImport>
    '/tempo-na-regiao-sul-rs': GeneratedFileRoute<'/tempo-na-regiao-sul-rs', typeof TempoNaRegiaoSulRsRouteImport>
    '/vento-em-pelotas': GeneratedFileRoute<'/vento-em-pelotas', typeof VentoEmPelotasRouteImport>
    '/widgets/nivel-laranjal.js': GeneratedFileRoute<'/widgets/nivel-laranjal.js', typeof WidgetsNivelLaranjalDotJsRouteImport>
  }
}

const rootRouteChildren = {
  IndexRoute,
  AlertasRoute,
  ApiAccountDeleteRoute,
  ApiAccountExportRoute,
  ApiCronEmbrapaRoute,
  ApiCronForecastAccuracyRoute,
  ApiCronPushDailyRoute,
  ApiCronWeatherSnapshotRoute,
  ApiInmetGeadasRoute,
  ApiPushBroadcastRoute,
  ApiPushConfigRoute,
  ApiPushSubscriptionRoute,
  ApiRedemetImageRoute,
  ApiRedemetRadarRoute,
  ApiRedemetSatelliteRoute,
  ApiRedemetStormsRoute,
  ApiWeatherEmbrapaRoute,
  ApiWeatherHourlyPrecipitationRoute,
  ApiWidgetsNivelLaranjalRoute,
  AuthCallbackRoute,
  AuthSignoutRoute,
  BlogRoute,
  BrandTempoPelotasHeaderRoute,
  BrandTempoPelotasIconDotPngRoute,
  BrandTempoPelotasMaskableDotPngRoute,
  CamerasAoVivoPelotasRoute,
  ChuvaEmPelotasRoute,
  ClimaEmPelotasRoute,
  ContaRoute,
  EmbedNivelLaranjalRoute,
  EmbedStatusTempoAgoraRoute,
  EntrarRoute,
  EstacaoEmbrapaPelotasRoute,
  FeedRoute,
  HistoricoClimaticoPelotasRoute,
  MapaDeGeadasRioGrandeDoSulRoute,
  MeteogramaPelotasRoute,
  MetodologiaRoute,
  MinhaContaRoute,
  NivelDaLagoaDosPatosLaranjalRoute,
  PelotasDotJsonRoute,
  Previsao7DiasPelotasRoute,
  PrivacidadeEDadosRoute,
  RadarESatelitePelotasRoute,
  RobotsDotTxtRoute,
  SitemapDotXmlRoute,
  SituacaoHidrologicaPelotasRoute,
  TempoAmanhaPelotasRoute,
  TempoEmCitySlugRoute,
  TempoHojePelotasRoute,
  TempoNaRegiaoSulRsRoute,
  VentoEmPelotasRoute,
  WidgetsNivelLaranjalDotJsRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
